### PR TITLE
Add support for Spartan 6 in xilinx_internal_jtag

### PR DESCRIPTION
**Pull request by mithro**
These patches from from @xfguo's repo at https://github.com/xfguo/adv_debug_sys/commits/master but rebased onto this tree.

There are two other patches in @xfguo's tree that you might want to pull but I don't understand things enough to check if they are actually correct;
- https://github.com/xfguo/adv_debug_sys/commit/e457aca4062573c163e774eaa5e19c5ed3ac8b34
- https://github.com/xfguo/adv_debug_sys/commit/db55d1166e04428327c115c819fa8fc32ca5bcf8

### CODE REVIEW

**Comment by xfguo** [comment]
Hi, more unfinished work is placed here https://github.com/xfguo/adv_debug_sys/commits/wip2 , maybe useful, but still need be reviewed and tested.

**Comment by mithro** [comment]
@xfguo Looks like you are working on Artix-7 BSCAN which would be awesome!

According to the people on the #openrisc IRC channel, a "improved" rewrite of this stuff is avaliable at https://github.com/RoaLogic/adv_dbg_if

If you are doing work on OpenRISC or RISC-V I highly recommending joining everyone on irc://irc.freenode.net/#openrisc IRC channel.

**Comment by xfguo** [comment]
@mithro Yes, I am doing some work on both OpenRISC and RISC-V. I will check the repo and IRC channel. Thanks.

**Comment by olofk** [comment]
Thanks @mithro and @xfguo. I'm pulling in these patches and hope to see even more in the future. It would be great to collect all the patches from the different version that is floating around the internet

**Pull request closed without merging**
